version: '3.8'

services:
  app:
    image: my-assignment-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis

  redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
